#On /.github/workflows
#hola-mundo.yml
name: hola-mundo-action
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Ejecutar script
        run: python hola_mundo.py
